version: '3.4'

services:
  boxti.dojointegrado.mysql:
    image: mysql:5.7

  adminer:
    image: adminer

  boxti.dojointegrado.api:
    image: ${DOCKER_REGISTRY-}boxtidojointegradoapi
    build:
      context: .
      dockerfile: src/BoxTI.DojoIntegrado.API/Dockerfile

volumes:
  mysqldb_data: