services:

  dojointegrado-db:
    container_name: dojointegrado_db
    image: mysql
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
